---
title: 'Tarea1 R'
subtitle: 'Tipos de Datos'
author: "Maria Alomoto"
date: '2022-02-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1
#### Crear un identificador de nombre "ciudad" y asigne como valor el nombre de alguna ciudad

ciudad <-"Quito"

## Ejercicio 2
#### Crear un identificador de nombre "pais_andes" y asigne como valor los nombres de los países por donde cruza la cordillera de Los Andes

pais_andes<- c("Argentina", "Bolivia", "Chile", "Colombia", "Ecuador", "Perú", "Venezuela")

# Ejercicio 3
#### Crear un dataframe con 12 eventos (files) y 5 variables (columnas),cada columna debe tener diferentes tipos de datos (entero, decimal,caracter, logico)

ejercicio3 = data.frame(eventos = seq(1:12),                         Calificacion = sample(0:10,12,replace = TRUE), 
                        Ciudad = c("Quito", "Latacunga","Tena", "Guayaquil", "Riobamba","Coca","cuenca","Quito","Coca","Guayaquil","Tena","Latacunga"), 
                        Promedio = c(7.8, 6.5, 9.1, 8.5, 5.9, 4.8, 5.3, 9.6, 7.2, 6.9, 8.8, 5.5))
                        
ejercicio3

## Ejercicio 4
#### Cargue el dataset "DNase" e identifique su estructura. Extraiga (subset) los datos que cumplan con las condiciones de:
1. "conc" (concentracion) entre 0.1 y 0.2
2. "Run" diferente a 2, "conc" mayor a 0.2 y "density" menor o igual a 1.0


install.packages("DNAse")

library(DNAse)

database<-DNase

class(DNase)

filtro1 <- filter(DNase, conc < 0.2 & conc > 0.1)

filtro2 <- filter(DNase, Run !=2 & conc > 0.2 & density <= 0.1)

library(dplyr)

conc <- filter(database,conc < 0.2 & conc > 0.1)



